# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    noir_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    noir_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

noir_arm_controller:
  ros__parameters:
    joints:
      - Base_joint
      - Shoulder_joint
      - Elbow_joint
      - Wrist_vertical_joint
      - Wrist_rotate_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
noir_gripper_controller:
  ros__parameters:
    joint: Gripper_joint